apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: goodner.jfrog.io/petclinic-docker/pet-clinicapp:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: petclinic
  type: LoadBalancer
